"""add_weight_to_answer_score_rules

Revision ID: 04b5d14bf50b
Revises: e7b67edb1b0a
Create Date: 2026-06-30 17:39:15.894439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b5d14bf50b'
down_revision: Union[str, Sequence[str], None] = 'e7b67edb1b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_score_rules', sa.Column('weight', sa.Numeric(), server_default=sa.text('1.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_score_rules', 'weight')
    # ### end Alembic commands ###
