"""created policy, recommendations and reports tables

Revision ID: 0fac261d7d7c
Revises: 35e5887b948e
Create Date: 2026-06-12 17:05:38.970025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fac261d7d7c'
down_revision: Union[str, Sequence[str], None] = '35e5887b948e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('insurer_id', sa.UUID(), nullable=False),
    sa.Column('insurance_category_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('min_sum_insured', sa.Numeric(), nullable=True),
    sa.Column('max_sum_insured', sa.Numeric(), nullable=True),
    sa.Column('key_features', sa.JSON(), nullable=True),
    sa.Column('target_segment', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insurance_category_id'], ['insurance_categories.id'], name=op.f('fk_policies_insurance_category_id_insurance_categories')),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], name=op.f('fk_policies_insurer_id_insurers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('insurance_category_id', sa.UUID(), nullable=False),
    sa.Column('risk_category_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Numeric(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name=op.f('fk_recommendations_business_id_business_profiles')),
    sa.ForeignKeyConstraint(['insurance_category_id'], ['insurance_categories.id'], name=op.f('fk_recommendations_insurance_category_id_insurance_categories')),
    sa.ForeignKeyConstraint(['risk_category_id'], ['risk_categories.id'], name=op.f('fk_recommendations_risk_category_id_risk_categories')),
    sa.ForeignKeyConstraint(['session_id'], ['profiling_sessions.id'], name=op.f('fk_recommendations_session_id_profiling_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'::character varying"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name=op.f('fk_reports_business_id_business_profiles')),
    sa.ForeignKeyConstraint(['session_id'], ['profiling_sessions.id'], name=op.f('fk_reports_session_id_profiling_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('recommendations')
    op.drop_table('policies')
    # ### end Alembic commands ###
