"""created profiling_sessions table

Revision ID: 156f315bb5c0
Revises: 81b8b87524c5
Create Date: 2026-06-12 16:59:14.186777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156f315bb5c0'
down_revision: Union[str, Sequence[str], None] = '81b8b87524c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiling_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'in_progress'::character varying"), nullable=False),
    sa.Column('current_section', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name=op.f('fk_profiling_sessions_business_id_business_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiling_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiling_sessions')
    # ### end Alembic commands ###
