"""created business_risk_score table

Revision ID: 35e5887b948e
Revises: f0dd2fdff3e2
Create Date: 2026-06-12 17:03:22.623505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e5887b948e'
down_revision: Union[str, Sequence[str], None] = 'f0dd2fdff3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_risk_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('risk_category_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('factor_breakdown', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name=op.f('fk_business_risk_scores_business_id_business_profiles')),
    sa.ForeignKeyConstraint(['risk_category_id'], ['risk_categories.id'], name=op.f('fk_business_risk_scores_risk_category_id_risk_categories')),
    sa.ForeignKeyConstraint(['session_id'], ['profiling_sessions.id'], name=op.f('fk_business_risk_scores_session_id_profiling_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_risk_scores'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_risk_scores')
    # ### end Alembic commands ###
