"""added foreignkey relationship to document_chunks table

Revision ID: 542862545bfb
Revises: 45cb78b78a4e
Create Date: 2026-06-18 16:00:29.612970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542862545bfb'
down_revision: Union[str, Sequence[str], None] = '45cb78b78a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_document_chunks_document_id_policy_documents'), 'document_chunks', 'policy_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_document_chunks_document_id_policy_documents'), 'document_chunks', type_='foreignkey')
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
