"""created business_profiles table

Revision ID: 81b8b87524c5
Revises: f727dde4d145
Create Date: 2026-06-12 16:58:04.979782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b8b87524c5'
down_revision: Union[str, Sequence[str], None] = 'f727dde4d145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_turnover_range', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_business_profiles_industry_id_industries')),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_business_profiles_segment_id_segments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_profiles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
