"""changes in the questions table for seeding questions

Revision ID: a46f0d47e055
Revises: 542862545bfb
Create Date: 2026-06-23 14:36:42.139368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46f0d47e055'
down_revision: Union[str, Sequence[str], None] = '542862545bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('unified_id', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('legacy_metadata', sa.JSON(), nullable=True))
    op.create_unique_constraint(op.f('uq_questions_unified_id'), 'questions', ['unified_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_questions_unified_id'), 'questions', type_='unique')
    op.drop_column('questions', 'legacy_metadata')
    op.drop_column('questions', 'unified_id')
    # ### end Alembic commands ###
