"""added relationships and auditmixin refactor

Revision ID: cc11db0de77b
Revises: 0fac261d7d7c
Create Date: 2026-06-15 15:34:58.454323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc11db0de77b'
down_revision: Union[str, Sequence[str], None] = '0fac261d7d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_industries_created_by_users'), 'industries', type_='foreignkey')
    op.drop_constraint(op.f('fk_industries_updated_by_users'), 'industries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_industries_created_by_users'), 'industries', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_industries_updated_by_users'), 'industries', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_segments_created_by_users'), 'segments', type_='foreignkey')
    op.drop_constraint(op.f('fk_segments_updated_by_users'), 'segments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_segments_created_by_users'), 'segments', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_segments_updated_by_users'), 'segments', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_segments_updated_by_users'), 'segments', type_='foreignkey')
    op.drop_constraint(op.f('fk_segments_created_by_users'), 'segments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_segments_updated_by_users'), 'segments', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_segments_created_by_users'), 'segments', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_industries_updated_by_users'), 'industries', type_='foreignkey')
    op.drop_constraint(op.f('fk_industries_created_by_users'), 'industries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_industries_updated_by_users'), 'industries', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_industries_created_by_users'), 'industries', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
