"""created question_factor_mapping and answer_score_rules tables

Revision ID: e60d4da764e3
Revises: 156f315bb5c0
Create Date: 2026-06-12 17:00:31.502555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60d4da764e3'
down_revision: Union[str, Sequence[str], None] = '156f315bb5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_score_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('risk_factor_id', sa.UUID(), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answer_score_rules_question_id_questions')),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], name=op.f('fk_answer_score_rules_risk_factor_id_risk_factors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_score_rules'))
    )
    op.create_table('question_factor_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('risk_factor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_factor_mappings_question_id_questions')),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], name=op.f('fk_question_factor_mappings_risk_factor_id_risk_factors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_factor_mappings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_factor_mappings')
    op.drop_table('answer_score_rules')
    # ### end Alembic commands ###
