"""created profiling_answers table

Revision ID: f0dd2fdff3e2
Revises: e60d4da764e3
Create Date: 2026-06-12 17:01:45.160433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dd2fdff3e2'
down_revision: Union[str, Sequence[str], None] = 'e60d4da764e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiling_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_profiling_answers_question_id_questions')),
    sa.ForeignKeyConstraint(['session_id'], ['profiling_sessions.id'], name=op.f('fk_profiling_answers_session_id_profiling_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiling_answers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiling_answers')
    # ### end Alembic commands ###
