"""created industry and questions tables

Revision ID: f727dde4d145
Revises: 526d9591c68d
Create Date: 2026-06-12 16:56:52.118941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f727dde4d145'
down_revision: Union[str, Sequence[str], None] = '526d9591c68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('applicable_segment', sa.String(), server_default=sa.text("'both'::character varying"), nullable=False),
    sa.Column('is_conditional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parent_question_id', sa.UUID(), nullable=True),
    sa.Column('parent_answer_value', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_question_id'], ['questions.id'], name=op.f('fk_questions_parent_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('industries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_industries_created_by_users')),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_industries_segment_id_segments')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_industries_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industries')
    op.drop_table('questions')
    # ### end Alembic commands ###
