"""Constants for authentication workflows."""

from app.shared.constants import USER_ROLE_NAME

AUTH_PREFIX = "/auth"
AUTH_TAG = "auth"

REGISTER_ROUTE = "/register"
LOGIN_ROUTE = "/login"
CHANGE_PASSWORD_ROUTE = "/change-password"
FORGOT_PASSWORD_ROUTE = "/forgot-password"
RESET_PASSWORD_ROUTE = "/reset-password"
REFRESH_ROUTE = "/refresh"
ME_ROUTE = "/me"
LOGOUT_ROUTE = "/logout"
PASSWORD_RESET_TOKEN_TYPE = "password_reset"
REFRESH_TOKEN_TYPE = "refresh"
TOKEN_TYPE_CLAIM = "type"
TOKEN_SUBJECT_CLAIM = "sub"
RESET_PASSWORD_QUERY_PATH = "/reset-password?token="

USER_ID_KEY = "id"
FULL_NAME_KEY = "full_name"
EMAIL_KEY = "email"
PHONE_KEY = "phone"
ROLE_KEY = "role"

USER_EXISTS_MESSAGE = "User with this email already exists"
USER_EMAIL_NOT_FOUND_MESSAGE = "User with this email does not exist"
ACCOUNT_INACTIVE_MESSAGE = "Account is inactive"
INVALID_EMAIL_OR_PASSWORD_MESSAGE = "Invalid email or password"
CURRENT_PASSWORD_INCORRECT_MESSAGE = "Current password is incorrect"
SAME_PASSWORD_MESSAGE = "New password cannot be same as current password"
PASSWORDS_DO_NOT_MATCH_MESSAGE = "Passwords do not match"
INVALID_TOKEN_MESSAGE = "Invalid token"
INVALID_TOKEN_TYPE_MESSAGE = "Invalid token type"
USER_NOT_FOUND_MESSAGE = "User not found"
RESET_TOKEN_NOT_FOUND_MESSAGE = "Reset token not found"
INVALID_REFRESH_TOKEN_MESSAGE = "Invalid refresh token"

USER_REGISTERED_MESSAGE = "User registered successfully"
USER_LOGGED_IN_MESSAGE = "User logged in successfully"
PASSWORD_CHANGED_MESSAGE = "Password changed successfully"
PASSWORD_RESET_EMAIL_SENT_MESSAGE = "Password reset email sent successfully"
TOKEN_REFRESHED_MESSAGE = "Token refreshed"
USER_FETCHED_MESSAGE = "User fetched successfully"
LOGGED_OUT_MESSAGE = "Logged out successfully"
