AUTH_ROUTER_PREFIX = "/auth"
AUTH_ROUTER_TAG = "auth"

REGISTER_ROUTE = "/register"
LOGIN_ROUTE = "/login"
CHANGE_PASSWORD_ROUTE = "/change-password"
FORGOT_PASSWORD_ROUTE = "/forgot-password"
RESET_PASSWORD_ROUTE = "/reset-password"
REFRESH_ROUTE = "/refresh"
LOGOUT_ROUTE = "/logout"

ACCESS_TOKEN_COOKIE = "access_token"
REFRESH_TOKEN_COOKIE = "refresh_token"
COOKIE_SAMESITE_LAX = "lax"

JWT_SUBJECT_KEY = "sub"
JWT_EMAIL_KEY = "email"
JWT_TYPE_KEY = "type"
JWT_EXPIRATION_KEY = "exp"
JWT_ACCESS_TYPE = "access"
JWT_REFRESH_TYPE = "refresh"
JWT_PASSWORD_RESET_TYPE = "password_reset"

ROLE_USER = "USER"

BCRYPT_SCHEME = "bcrypt"
PASSLIB_DEPRECATED_AUTO = "auto"

RESET_PASSWORD_FRONTEND_PATH = "/reset-password"
RESET_PASSWORD_TOKEN_QUERY = "?token="

PASSWORD_FIELD = "password"
EMAIL_FIELD = "email"
PHONE_NUMBER_FIELD = "phone_no"
NEW_PASSWORD_FIELD = "new_password"
MODEL_VALIDATOR_AFTER = "after"
PHONE_START_DIGIT_6 = "6"
PHONE_START_DIGIT_7 = "7"
PHONE_START_DIGIT_8 = "8"
PHONE_START_DIGIT_9 = "9"

PASSWORDS_DO_NOT_MATCH = "Passwords do not match"
PASSWORD_MIN_LENGTH_MESSAGE = "Password must be at least 8 characters"
PASSWORD_UPPERCASE_MESSAGE = "Password must contain at least one uppercase letter"
PASSWORD_NUMBER_MESSAGE = "Password must contain at least one number"
PHONE_DIGITS_ONLY_MESSAGE = "Please enter a valid 10-digit mobile number."
PHONE_EXACT_LENGTH_MESSAGE = "Please enter a valid 10-digit mobile number."
INVALID_PHONE_NUMBER_MESSAGE = "Please enter a valid 10-digit mobile number."

USER_EMAIL_EXISTS_MESSAGE = "User with this email already exists"
USER_REGISTERED_MESSAGE = "User registered successfully"
USER_EMAIL_NOT_FOUND_MESSAGE = "User with this email does not exist"
ACCOUNT_INACTIVE_MESSAGE = "Account is inactive"
INVALID_EMAIL_OR_PASSWORD_MESSAGE = "Invalid email or password"
USER_LOGGED_IN_MESSAGE = "User logged in successfully"
CURRENT_PASSWORD_INCORRECT_MESSAGE = "Current password is incorrect"
NEW_PASSWORD_SAME_MESSAGE = "New password cannot be same as current password"
PASSWORD_CHANGED_MESSAGE = "Password changed successfully"
PASSWORD_RESET_EMAIL_SENT_MESSAGE = "Password reset email sent successfully"
INVALID_TOKEN_MESSAGE = "Invalid token"
INVALID_TOKEN_TYPE_MESSAGE = "Invalid token type"
USER_NOT_FOUND_MESSAGE = "User not found"
RESET_TOKEN_NOT_FOUND_MESSAGE = "Reset token not found"
INVALID_REFRESH_TOKEN_MESSAGE = "Invalid refresh token"
TOKEN_REFRESHED_MESSAGE = "Token refreshed"
LOGGED_OUT_MESSAGE = "Logged out successfully"

FULL_NAME_RESPONSE_KEY = "full_name"
EMAIL_RESPONSE_KEY = "email"
PHONE_RESPONSE_KEY = "phone"
